version: 0.2

env:
  variables:
    MIX_ENV: "prod"

phases:
  install:
    commands:
      - mix local.hex --force
      - mix deps.get
  pre_build:
    commands:
      - mix compile 
      - mix test
  build:
    commands:
      - mix distillery.release
  post_build:
    commands:

artifacts:
  files:
    - _build/*
    - appspec.yml
  discard-paths: yes
