version: 0.2

env:
  variables:
    MIX_ENV: "prod"

phases:
  install:
    commands:
      - mix local.hex --force
      - mix deps.get
  pre_build:
    commands:
      - mix compile 
      - mix test
  build:
    commands:
      - mix distillery.release
  post_build:
    commands:
      - tar zcvf release.tgz _build appspec.yml

artifacts:
  files:
    - _build/**/*
  discard-paths: no
