version: 0.2

env:
  variables:
    MIX_ENV: "prod"

phases:
  install:
    commands:
      - mix local.hex --force
      - mix deps.get
      - chmod 755 bin/export
  pre_build:
    commands:
      - mix compile 
      - mix test
  build:
    commands:
      - mix distillery.release
  post_build:
    commands:
      - bin/export

artifacts:
  files:
    - '*.tgz'
  discard-paths: no
